language: python
python:
  - "2.6"
  - "2.7"
install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install pep8
script:
  - nosetests
  - pep8 wphardening
after_success: coveralls
sudo: false
